<Window x:Class="WpfExceptionHandling.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfExceptionHandling"
        mc:Ignorable="d"
        Title="WpfExceptionHandling Project" Height="450" Width="500"
        d:DataContext="{x:Type local:MainVM}">
    <Grid>
        <Button x:Name="button" Content="Exception" HorizontalAlignment="Left" Margin="63,50,0,0" VerticalAlignment="Top" Click="Button_Click"/>
        <Button x:Name="asyncButton" Content="Async Exception" HorizontalAlignment="Left" Margin="63,90,0,0" VerticalAlignment="Top" Click="AsyncButton_Click"/>
        <Button x:Name="commandButton" Content="Command Button" HorizontalAlignment="Left" Margin="63,129,0,0" VerticalAlignment="Top" Command="{Binding ClickCommand}"/>
        <Button x:Name="buttonBeginInvoke" Content="Begin Invoke" HorizontalAlignment="Left" Margin="63,166,0,0" VerticalAlignment="Top" RenderTransformOrigin="0.136,0.597" Click="ButtonBeginInvoke_Click"/>
        <Button x:Name="taskRunButton" Content="Task.Run()" HorizontalAlignment="Left" Margin="63,202,0,0" VerticalAlignment="Top" Click="TaskRunButton_Click"/>
    </Grid>
</Window>
